// Module included in the following assemblies:
//
// doc-mtv_2.0/master.adoc

[id="creating-a-migration-plan_{context}"]
= Creating a migration plan

You can create a migration plan in the {mtv-short} console. 

A migration plan allows you to group virtual machines that should be migrated together or with the same migration parameters, for example, a percentage of the members of a cluster or a complete application.

[discrete]
== Prerequisites

* You have added the source and target providers to the {mtv-short} console.
* You have ensured that the migration network is optimal for migration.
* You have created a network mapping.
* You have created a storage mapping.

[discrete]
== Procedure

. In the {mtv-short} console, navigate to *Migration plans* and click *Create migration plan*.
. Fill in the following fields in the *General settings* screen:
* *Plan name*: Name of the migration plan. Limitations? characters? Length?
* *Plan description*: Optional: description of the migration plan.
* *Source provider*: Select a VMware provider.
* *Target provider*: Select an {virt} provider.

. Click *Next*.
. Filter the VMs that you want to migrate by selecting a data centers, clusters, or folders.
. Select the VMs to migrate. You can click each VM to view its migration risk assessment.
. Select an existing storage mapping or create a new storage mapping.
. If you want to create a new storage mapping, select one or more source data stores in the left pane and drag and drop them on the associated target storage classes in the right pane.
. Click *Next*.
. Select an existing network mapping or create a new network mapping.
. If you want to create a new network mapping, select one or more source networks on the left pane and drag and drop them on the associated target networks in the right pane.
. Click *Next*.
. If you want to add a hook to the migration plan:

.. Select an existing hook from the list or click *Add hook*.
.. Select *Ansible playbook* or *Custom container image* as the hook definition.
.. Select the migration step when you want the hook to run.
.. Click *Add*.

. Click *Next*.
. Review your migration plan and click *Finish*.
+
The migration plan is saved in the migration plan list.